#!/usr/bin/env node
/**
 * @p31/canon-react — build-css.mjs
 *
 * tsup does not emit CSS. Each component stylesheet lives under src and ends
 * in .css; this concatenates them (in deterministic sorted order) into
 * dist/styles.css so the `./styles.css` export resolves. CSS `@layer` blocks
 * with the same name re-open rather than duplicate, so plain concatenation
 * is safe as component count grows.
 *
 * Run after `tsup` — wired as `build`: "tsup && node scripts/build-css.mjs".
 */
import { mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, resolve, dirname, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const srcDir = join(root, 'src');

/** Walk srcDir, collect every *.css path in sorted order. */
function collect(dir, out) {
  for (const name of readdirSync(dir).sort()) {
    if (name.startsWith('.')) continue;
    const full = join(dir, name);
    if (statSync(full).isDirectory()) {
      collect(full, out);
      continue;
    }
    if (name.endsWith('.css')) out.push(full);
  }
  return out;
}

const files = collect(srcDir, []);
if (files.length === 0) {
  console.error('build-css: no *.css files under src/ — dist/styles.css not written');
  process.exit(1);
}

mkdirSync(join(root, 'dist'), { recursive: true });
const banner =
  '/*\n * @p31/canon-react — styles.css. Generated by scripts/build-css.mjs.\n * Concatenated from component stylesheets under src (sorted).\n * Do not edit directly; run `pnpm build`.\n */\n\n';
const body = files.map((f) => {
  const rel = f.replace(root + sep, '').replace(/\\/g, '/');
  return `/* ── ${rel} ──────────────────────────────── */\n` + readFileSync(f, 'utf8').trim();
}).join('\n\n');

writeFileSync(join(root, 'dist', 'styles.css'), banner + body + '\n');
console.log(`build-css: ${files.length} stylesheet(s) → dist/styles.css (${banner.length + body.length} bytes)`);