name = "p31-signaling"
main = "src/index.ts"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "P31_SIGNALING_KV", id = "9401942b1098497caec0fe095809c7b3" }
]

[[durable_objects.bindings]]
name = "SIGNALING_ROOM"
class_name = "SignalingRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SignalingRoom"]
