// vector.mjs — Known-answer test vector for taler_cs.wasm (CBS over Ed25519).
//
// Gates from AXIS-1_FINAL_DELIVERABLE.md §7:
//   1. WASM builds               -> built via cargo (see build.sh)
//   2. round-trip verify == true -> blind -> sign -> unblind -> verify
//   3. tampered s'   -> verify == false  (the property the broken
//      XOR 'return 0' stub FAILED)
//
// Strong cross-check: issuer public key X and ephemeral nonce R are
// generated by Node Web Crypto (an INDEPENDENT Ed25519 implementation)
// and fed to the wasm. The scalar x (resp. n) is derived from the
// seed the same way RFC 8032 derives it (clamp low32 of SHA-512).
// Any divergence between the two implementations fails the test.

import { readFileSync, promises as fs } from 'node:fs';
import { webcrypto } from 'node:crypto';

const crypto = webcrypto;
// Resolve the artifact: prefer the committed prebuilt, fall back to a local build.
const CANDIDATES = [
  new URL('../src/taler_cs.wasm', import.meta.url),
  new URL('../target/wasm32-unknown-unknown/release/taler_cbs.wasm', import.meta.url),
];
let WASM = null;
for (const c of CANDIDATES) {
  try {
    await fs.access(c);
    WASM = c;
    break;
  } catch {}
}
if (!WASM) {
  console.error('FAIL: taler_cs.wasm not found (build first or commit the prebuilt)');
  process.exit(1);
}
const buf = readFileSync(WASM);

const { instance } = await WebAssembly.instantiate(buf, { env: {} });
const ex = instance.exports;
const mem = ex.memory;

// Safe region: above Rust data/stack, within the single memory page set.
const HEAP = Math.ceil(ex.__heap_base.value / 1024) * 1024;
const OFF_MSG = HEAP + 0; // message (<=1024)
const OFF_A = HEAP + 2048; // a / s / scratch
const OFF_B = HEAP + 3072; // b / n / scratch
const OFF_R = HEAP + 4096; // R
const OFF_X = HEAP + 5120; // X
const OFF_C = HEAP + 6144; // c (32) + c' (32)
const OFF_CP = OFF_C + 32;
const OFF_S = HEAP + 7168; // s / s'

const U8 = (off, n) => new Uint8Array(mem.buffer, off, n);
const write = (off, d) => U8(off, d.length).set(d);
const read = (off, n) => U8(off, n).slice();
const rnd = () => crypto.getRandomValues(new Uint8Array(32));
const clamp32 = (seed) => {
  const x = seed.slice(0, 32);
  x[0] &= 248;
  x[31] &= 127;
  x[31] |= 64;
  return x;
};
const eq = (a, b) => a.length === b.length && a.every((v, i) => v === b[i]);

// Derive (scalar, publicPoint) the RFC 8032 way, using Web Crypto keys.
async function ed25519Scalars() {
  const kp = await crypto.subtle.generateKey('Ed25519', true, ['sign', 'verify']);
  const jwk = await crypto.subtle.exportKey('jwk', kp.privateKey);
  const pub = new Uint8Array(Buffer.from(jwk.x, 'base64url'));
  const seed = new Uint8Array(Buffer.from(jwk.d, 'base64url'));
  const h = new Uint8Array(await crypto.subtle.digest('SHA-512', seed));
  const scalar = clamp32(h);
  return { pub, scalar };
}

// --- Issuer keypair (X) and ephemeral nonce (R) from Web Crypto ---
const issuer = await ed25519Scalars();
const ephemeral = await ed25519Scalars();
const X = issuer.pub;
const x = issuer.scalar;
const R = ephemeral.pub;
const n = ephemeral.scalar;

// --- Client blinds message m with random a, b ---
const m = new TextEncoder().encode('authorize 5 LOVE -> creator p31');
const a = rnd();
const b = rnd();
write(OFF_MSG, m);
write(OFF_A, a);
write(OFF_B, b);
write(OFF_R, R);
write(OFF_X, X);
if (ex.cs_blind(OFF_MSG, m.length, OFF_A, OFF_B, OFF_R, OFF_X, OFF_C, OFF_CP) !== 0) {
  console.error('FAIL: cs_blind');
  process.exit(1);
}
const c = read(OFF_C, 32); // blinded challenge c = c' + b
const cPrime = read(OFF_CP, 32); // kept by client
console.log('OK   blind: produced c (sent to issuer) and c\' (kept)');

// --- Issuer signs c with n, x ---
write(OFF_A, c);
write(OFF_B, n);
write(OFF_X, x);
if (ex.cs_sign_blinded(OFF_A, OFF_B, OFF_X, OFF_S) !== 0) {
  console.error('FAIL: cs_sign_blinded');
  process.exit(1);
}
const s = read(OFF_S, 32);
console.log('OK   sign: s = n + c·x');

// --- Client unblinds s -> s' ---
write(OFF_A, s);
write(OFF_B, a);
if (ex.cs_unblind(OFF_A, OFF_B, OFF_S) !== 0) {
  console.error('FAIL: cs_unblind');
  process.exit(1);
}
const sPrime = read(OFF_S, 32);
console.log('OK   unblind: s\' = s + a');

// --- Verify (valid signature) ---
write(OFF_MSG, m);
write(OFF_A, cPrime);
write(OFF_B, sPrime);
write(OFF_X, X);
write(OFF_R, R);
const valid = ex.cs_verify(OFF_MSG, m.length, OFF_A, OFF_B, OFF_X, OFF_R) === 0;
if (!valid) {
  console.error('FAIL: valid CBS signature (cross-checked w/ Web Crypto points) rejected');
  process.exit(1);
}
console.log('OK   verify: round-trip signature VALID (wasm == independent Ed25519)');

// --- Verify (tampered s') -> must be INVALID (catches return-0 bug) ---
const tampered = sPrime.slice();
tampered[0] ^= 0xff;
write(OFF_A, cPrime);
write(OFF_B, tampered);
if (ex.cs_verify(OFF_MSG, m.length, OFF_A, OFF_B, OFF_X, OFF_R) === 0) {
  console.error('FAIL: tampered signature accepted (broken-verify regression)');
  process.exit(1);
}
console.log('OK   verify: tampered s\' REJECTED (no return-0 bug)');

// --- Verify (wrong message) -> must be INVALID ---
const wrongMsg = new TextEncoder().encode('authorize 5000 LOVE -> attacker');
write(OFF_MSG, wrongMsg);
write(OFF_A, cPrime);
write(OFF_B, sPrime);
if (ex.cs_verify(OFF_MSG, wrongMsg.length, OFF_A, OFF_B, OFF_X, OFF_R) === 0) {
  console.error('FAIL: wrong-message signature accepted');
  process.exit(1);
}
console.log('OK   verify: wrong message REJECTED');

// --- Sanity: random (c', s') -> INVALID (catches always-true verify) ---
write(OFF_A, rnd());
write(OFF_B, rnd());
if (ex.cs_verify(OFF_MSG, wrongMsg.length, OFF_A, OFF_B, OFF_X, OFF_R) === 0) {
  console.error('FAIL: random signature accepted (verify always-true)');
  process.exit(1);
}
console.log('OK   verify: random signature REJECTED');

// --- Self-consistency over many random trials ---
for (let i = 0; i < 12; i++) {
  const mm = crypto.getRandomValues(new Uint8Array(1 + (i % 40)));
  const aa = rnd();
  const bb = rnd();
  write(OFF_MSG, mm);
  write(OFF_A, aa);
  write(OFF_B, bb);
  write(OFF_R, R);
  write(OFF_X, X);
  if (ex.cs_blind(OFF_MSG, mm.length, OFF_A, OFF_B, OFF_R, OFF_X, OFF_C, OFF_CP) !== 0) {
    console.error('FAIL: blind trial', i);
    process.exit(1);
  }
  const cc = read(OFF_C, 32);
  const ccp = read(OFF_CP, 32);
  write(OFF_A, cc);
  write(OFF_B, n);
  write(OFF_X, x);
  if (ex.cs_sign_blinded(OFF_A, OFF_B, OFF_X, OFF_S) !== 0) {
    console.error('FAIL: sign trial', i);
    process.exit(1);
  }
  write(OFF_A, read(OFF_S, 32));
  write(OFF_B, aa);
  if (ex.cs_unblind(OFF_A, OFF_B, OFF_S) !== 0) {
    console.error('FAIL: unblind trial', i);
    process.exit(1);
  }
  write(OFF_MSG, mm);
  write(OFF_A, ccp);
  write(OFF_B, read(OFF_S, 32));
  write(OFF_X, X);
  write(OFF_R, R);
  if (ex.cs_verify(OFF_MSG, mm.length, OFF_A, OFF_B, OFF_X, OFF_R) !== 0) {
    console.error('FAIL: round-trip trial', i);
    process.exit(1);
  }
}
console.log('OK   12 randomized round-trips all VALID');

console.log('\nALL GATES PASSED — taler_cs.wasm is a real, verified Clause Blind Schnorr.');
