// Generated by Wrangler by running `wrangler types`

interface Env {
	KV: KVNamespace;
	PSK: "replace-me-with-actual-psk";
	ENVIRONMENT: "production";
	ORCHESTRATOR_DO: DurableObjectNamespace<import("./src/index").OrchestratorDO>;
	R2_BUCKET: R2Bucket;
	DB: D1Database;
}
