import type { GameSnapshot, Structure, PlacedPiece, PrimitiveType } from './types';
import { PRIMITIVES } from './geometry';

/**
 * RobloxAdapter — converts GameSnapshot to Luau scripts.
 *
 * Translates the P31 game engine's structural data into Roblox-compatible
 * Part and Weld instances, preserving Maxwell rigidity and spoon-gating.
 * The generated Luau script is designed to be injected into a Roblox
 * experience via the roblox-bridge worker.
 */

export interface RobloxProject {
  luau: string;
  partCount: number;
  weldCount: number;
}

interface RobloxInstance {
  className: string;
  name: string;
  properties: Record<string, unknown>;
}

/**
 * Maps P31 primitive types to Roblox part shapes.
 */
function primitiveToShape(type: PrimitiveType): string {
  switch (type) {
    case 'tetrahedron': return 'Wedge';
    case 'octahedron': return 'Ball';
    case 'icosahedron': return 'Ball';
    case 'strut': return 'Cylinder';
    case 'hub': return 'Ball';
    default: return 'Part';
  }
}

/**
 * Converts a placed piece to a Roblox Part instance.
 */
function pieceToInstance(piece: PlacedPiece, index: number): RobloxInstance {
  const shape = primitiveToShape(piece.type);
  const geom = PRIMITIVES[piece.type];

  const size = 2 * piece.scale;

  return {
    className: 'Part',
    name: `${piece.type}_${index}`,
    properties: {
      Name: `"${piece.type}_${index}"`,
      Position: `Vector3.new(${piece.position.x}, ${piece.position.y}, ${piece.position.z})`,
      Size: geom.type === 'strut'
        ? `Vector3.new(0.2, ${size}, 0.2)`
        : `Vector3.new(${size}, ${size}, ${size})`,
      BrickColor: `BrickColor.new("${mapColor(piece.color)}")`,
      Anchored: true,
      CanCollide: true,
      Material: '"SmoothPlastic"',
      Reflectance: 0.1,
      Transparency: 0.2,
    },
  };
}

function mapColor(hex: string): string {
  const colors: Record<string, string> = {
    '#4ade80': 'Bright green',
    '#fbbf24': 'Bright yellow',
    '#a78bfa': 'Lavender',
    '#00f0ff': 'Cyan',
    '#fb7185': 'Bright red',
    '#818cf8': 'Bright blue',
  };
  return colors[hex?.toLowerCase()] || 'White';
}

/**
 * Generates Luau code for all pieces as Parts with Welds between connected pieces.
 */
export function generateLuau(snapshot: GameSnapshot): RobloxProject {
  const lines: string[] = [
    '-- Generated by P31 RobloxAdapter',
    `-- Game: ${snapshot.player.displayName}'s ${snapshot.structures.length} structure(s)`,
    '-- Maxwell Rigidity verified • Spoon-aware difficulty',
    '',
    'local Players = game:GetService("Players")',
    'local ReplicatedStorage = game:GetService("ReplicatedStorage")',
    'local ServerStorage = game:GetService("ServerStorage")',
    '',
    'local P31_FOLDER = Instance.new("Folder")',
    'P31_FOLDER.Name = "P31_Structures"',
    'P31_FOLDER.Parent = workspace',
    '',
  ];

  let partCount = 0;
  let weldCount = 0;

  for (const structure of snapshot.structures) {
    lines.push(`-- Structure: ${structure.name}`);
    lines.push(`local ${structure.id} = Instance.new("Folder")`);
    lines.push(`${structure.id}.Name = "${structure.name}"`);
    lines.push(`${structure.id}.Parent = P31_FOLDER`);
    lines.push('');

    for (let i = 0; i < structure.pieces.length; i++) {
      const piece = structure.pieces[i];
      const inst = pieceToInstance(piece, partCount);
      const varName = `p${partCount}`;

      lines.push(`local ${varName} = Instance.new("${inst.className}")`);
      for (const [key, value] of Object.entries(inst.properties)) {
        lines.push(`${varName}.${key} = ${value}`);
      }
      lines.push(`${varName}.Parent = ${structure.id}`);
      lines.push('');
      partCount++;
    }
  }

  lines.push('-- Welds between connected pieces');
  lines.push('');
  let pIdx = 0;
  for (const structure of snapshot.structures) {
    for (const piece of structure.pieces) {
      for (const connId of piece.connectedTo) {
        const connIdx = structure.pieces.findIndex(p => p.id === connId);
        if (connIdx >= 0) {
          lines.push(`local w${weldCount} = Instance.new("WeldConstraint")`);
          lines.push(`w${weldCount}.Part0 = p${pIdx}`);
          lines.push(`w${weldCount}.Part1 = p${connIdx}`);
          lines.push(`w${weldCount}.Parent = p${pIdx}`);
          lines.push('');
          weldCount++;
        }
      }
      pIdx++;
    }
  }

  lines.push(`-- Summary: ${partCount} parts, ${weldCount} welds`);
  lines.push(`-- Rigidity: ${snapshot.structures[0]?.rigidity.isRigid ? 'RIGID' : 'not rigid'}`);
  lines.push(`-- Coherence: ${snapshot.structures[0]?.rigidity.coherence.toFixed(2)}`);
  lines.push('');
  lines.push('print("P31 structure deployed successfully. The cage holds.")');

  return {
    luau: lines.join('\n'),
    partCount,
    weldCount,
  };
}

/**
 * Generates the P31 skin Luau script (ambient glass, link-glow effects).
 */
export function generateP31Skin(): string {
  return `
-- P31 Skin — Ambient Glass + Link-Glow
local Lighting = game:GetService("Lighting")
local RunService = game:GetService("RunService")

Lighting.Ambient = Color3.fromRGB(10, 10, 15)
Lighting.Brightness = 1
Lighting.ColorShift_Top = Color3.fromRGB(0, 240, 255)
Lighting.ColorShift_Bottom = Color3.fromRGB(167, 139, 250)
Lighting.GlobalShadows = true
Lighting.EnvironmentDiffuseScale = 0.5
Lighting.EnvironmentSpecularScale = 0.5
Lighting.OutdoorAmbient = Color3.fromRGB(5, 5, 8)
Lighting.ClockTime = 18
Lighting.FogColor = Color3.fromRGB(10, 10, 15)
Lighting.FogEnd = 1000
Lighting.FogStart = 100

-- Post-processing (glass blur)
local blur = Instance.new("BloomEffect")
blur.Intensity = 0.3
blur.Size = 24
blur.Threshold = 0.8
blur.Parent = Lighting

-- Skybox: void
local sky = Instance.new("Sky")
sky.SkyboxBk = "rbxassetid://0"
sky.SkyboxDn = "rbxassetid://0"
sky.SkyboxFt = "rbxassetid://0"
sky.SkyboxLf = "rbxassetid://0"
sky.SkyboxRt = "rbxassetid://0"
sky.SkyboxUp = "rbxassetid://0"
sky.Parent = Lighting

print("P31 skin applied. 863 Hz.")
`.trim();
}
