name = "love-ledger"
main = "index.ts"
compatibility_date = "2026-01-01"

[placement]
mode = "smart"

[env.production]
retries = 3

[env.staging]
retries = 3

[[d1_databases]]
binding = "LOVE_DB"
database_name = "love-ledger"
database_id = "592e3e2e-3203-4e0a-8342-9e85215ec8a6"

[observability]
enabled = true

[[migrations]]
tag = "v1"
