import type { Axis } from '../types/index.js';

export interface JitterbugDimension {
  dimension: 'CODE' | 'TEST' | 'DOCS' | 'OPS' | 'SEC';
  score: number;
  weight: number;
}

export class MaturityScorer {
  scoreDeliverable(deliverable: { filePath: string; description: string }): JitterbugDimension[] {
    const ext = deliverable.filePath.split('.').pop()?.toLowerCase() || '';
    const isTest = /test|spec/i.test(deliverable.filePath) || /test|spec/i.test(deliverable.description);
    const isDoc = /\.md$|\.txt$|\.rst$/i.test(ext) || /doc|readme|guide/i.test(deliverable.filePath);
    const isConfig = /wrangler\.toml|docker-compose|\.env|deploy/i.test(deliverable.filePath);
    const isSecurity = /security|trust|auth|crypto|eigentrust/i.test(deliverable.description);

    const dimensions: JitterbugDimension[] = [];

    if (isTest) {
      dimensions.push({ dimension: 'TEST', score: 1.0, weight: 0.3 });
      dimensions.push({ dimension: 'CODE', score: 0.8, weight: 0.1 });
    } else if (isDoc) {
      dimensions.push({ dimension: 'DOCS', score: 1.0, weight: 0.25 });
    } else if (isConfig) {
      dimensions.push({ dimension: 'OPS', score: 1.0, weight: 0.2 });
    } else if (isSecurity) {
      dimensions.push({ dimension: 'SEC', score: 1.0, weight: 0.3 });
      dimensions.push({ dimension: 'TEST', score: 0.6, weight: 0.15 });
    } else {
      dimensions.push({ dimension: 'CODE', score: 1.0, weight: 0.25 });
      dimensions.push({ dimension: 'TEST', score: 0.5, weight: 0.1 });
    }

    return dimensions;
  }

  scoreAxis(axis: Axis): JitterbugDimension[] {
    const allDimensions: JitterbugDimension[] = [];
    for (const deliverable of axis.deliverable) {
      allDimensions.push(...this.scoreDeliverable(deliverable));
    }
    return this.mergeDimensions(allDimensions);
  }

  private mergeDimensions(dims: JitterbugDimension[]): JitterbugDimension[] {
    const map = new Map<string, { total: number; weight: number; count: number }>();
    for (const dim of dims) {
      const existing = map.get(dim.dimension) || { total: 0, weight: 0, count: 0 };
      existing.total += dim.score * dim.weight;
      existing.weight += dim.weight;
      existing.count++;
      map.set(dim.dimension, existing);
    }
    return Array.from(map.entries()).map(([dimension, data]) => ({
      dimension: dimension as JitterbugDimension['dimension'],
      score: data.weight > 0 ? data.total / data.weight : 0,
      weight: data.weight / data.count,
    }));
  }
}

export class SignalEmitter {
  private signals: Record<string, { weight: number; artifacts: string[] }>;

  constructor(initialSignals?: Record<string, { weight: number; artifacts: string[] }>) {
    this.signals = initialSignals || {};
  }

  emitFromAxis(axis: Axis): void {
    const signalName = `axis_completed:${axis.id}`;
    const artifacts = axis.deliverable.map((d: { filePath: string }) => d.filePath);
    const weight = axis.complexity === 'high' ? 1.0 : axis.complexity === 'medium' ? 0.8 : 0.6;
    this.signals[signalName] = { weight, artifacts };
  }

  getSignals(): Record<string, { weight: number; artifacts: string[] }> {
    return { ...this.signals };
  }

  toJitterbugSignalsFormat(): Record<string, unknown> {
    const formatted: Record<string, unknown> = { ...this.signals };
    formatted._comment = `Auto-generated by brain-dump-orchestrator for batch ${new Date().toISOString().split('T')[0]}`;
    formatted._schema = 'PMM_JITTERBUG=1.0';
    return formatted;
  }
}

export class StageTransitionTracker {
  private stages: Map<string, { from: string; to: string; timestamp: string }> = new Map();

  recordTransition(axisId: string, from: string, to: string): void {
    this.stages.set(axisId, { from, to, timestamp: new Date().toISOString() });
  }

  getTransitions(): Map<string, { from: string; to: string; timestamp: string }> {
    return new Map(this.stages);
  }

  getTransitionCount(): number {
    return this.stages.size;
  }
}
