// Generated by Wrangler by running `wrangler types`

interface Env {
	EDGE_AI_URL: "https://phos-ai-backend.trimtab-signal.workers.dev";
	JITTERBUG_API_URL: "https://jitterbug-api.trimtab-signal.workers.dev";
	AI: Ai;
}
