name = "p31-telemetry"
main = "src/worker.ts"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
vars = { ALLOWED_ORIGIN = "https://p31ca.org" }

[[kv_namespaces]]
binding = "TELEMETRY_KV"
id = "3293820df2b94398a183270a0cac8c7e"
