name = "contract-engine"
main = "index.ts"
compatibility_date = "2026-01-01"

[placement]
mode = "smart"

[env.production]
retries = 3

[env.staging]
retries = 3

[[d1_databases]]
binding = "LOVE_DB"
database_name = "love-ledger"
database_id = "592e3e2e-3203-4e0a-8342-9e85215ec8a6"

[[d1_databases]]
binding = "CONTRACTS_DB"
database_name = "contracts-db"
database_id = "f0e9df39-fa25-4307-b2a0-342ecff7b24e"

[durable_objects]
bindings = [
  { name = "CONTRACT_ENGINE", class_name = "ContractEngine" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ContractEngine"]

[observability]
enabled = true
