/**
 * Build script: inlines docs/openapi.yaml into a Worker-compatible module.
 * Run before deploy: node scripts/generate-openapi.ts
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const yaml = readFileSync(join(__dirname, '../../docs/openapi.yaml'), 'utf-8');

const escaped = yaml
  .replace(/\\/g, '\\\\')
  .replace(/`/g, '\\`')
  .replace(/\$/g, '\\$');

const content = `// Auto-generated by scripts/generate-openapi.ts — do not edit manually
export const OPENAPI_YAML = \`${escaped}\`;
`;

writeFileSync(join(__dirname, '../src/endpoints/openapi.generated.ts'), content);
console.log('✅ Generated src/endpoints/openapi.generated.ts');
