import { readFileSync, writeFileSync } from 'fs';

const path = 'src/generator/adapters/react.ts';
const lines = readFileSync(path, 'utf-8').split('\n');

// Find line 575 (0-indexed: 574) which is the closing }; of COMPONENT_TEMPLATES
const insertIndex = lines.findIndex((line, i) => i === 574 && line.trim() === '};');
if (insertIndex === -1) {
  console.error('Could not find insertion point at line 575');
  process.exit(1);
}

const newTemplates = [
  '',
  '  Topbar: (name, def) => `/**',
  ' * @file ${name} — Fixed glass navigation header.',
  ' * Auto-generated from components.yml.',
  ' */',
  '',
  'import type { ReactNode } from \'react\';',
  '',
  'export interface ${name}Props {',
  '  brand?: ReactNode;',
  '  left?: ReactNode;',
  '  center?: ReactNode;',
  '  right?: ReactNode;',
  '  className?: string;',
  '  style?: React.CSSProperties;',
  '}',
  '',
  'export function ${name}({ brand, left, center, right, className, style }: ${name}Props) {',
  '  const cls = `topbar glass-navbar ${className || \\\'\\\'}`;',
  '  return (',
  '    <header className={cls} style={style}>',
  '      <div className="topbar-left">{brand || left}</div>',
  '      <div className="topbar-center">{center}</div>',
  '      <div className="topbar-right">{right}</div>',
  '    </header>',
  '  );',
  '}',
  '',
  'export default ${name};',
  '`,',
  '',
  '  BottomNav: (name, def) => `/**',
  ' * @file ${name} — Fixed bottom navigation bar for mobile-first apps.',
  ' * Auto-generated from components.yml.',
  ' */',
  '',
  'import type { ReactNode } from \'react\';',
  '',
  'export interface NavItem {',
  '  icon: ReactNode;',
  '  label: string;',
  '  href: string;',
  '  active?: boolean;',
  '}',
  '',
  'export interface ${name}Props {',
  '  items: NavItem[];',
  '  activeIndex?: number;',
  '  className?: string;',
  '}',
  '',
  'export function ${name}({ items, activeIndex = 0, className }: ${name}Props) {',
  '  return (',
  '    <nav className={`bottom-nav ${className || \\\'\\\'}`} role="navigation" aria-label="Main">',
  '      {items.map((item, i) => (',
  '        <a',
  '          key={i}',
  '          href={item.href}',
  '          className={`nav-item ${i === activeIndex ? \\\'active\\\' : \\\'\\\'}`}',
  '          aria-current={i === activeIndex ? \\\'page\\\' : undefined}',
  '        >',
  '          {item.icon}',
  '          <span>{item.label}</span>',
  '        </a>',
  '      ))}',
  '    </nav>',
  '  );',
  '}',
  '',
  'export default ${name};',
  '`,',
  '',
  '  SpoonDial: (name, def) => `/**',
  ' * @file ${name} — Cognitive load selector (0-5 spoons).',
  ' * Auto-generated from components.yml.',
  ' */',
  '',
  'import type { ReactNode } from \'react\';',
  '',
  'export interface ${name}Props {',
  '  level: number;',
  '  onChange?: (level: number) => void;',
  '  className?: string;',
  '}',
  '',
  'const SPOON_SVG = `<svg viewBox="0 0 200 200" width="15" height="15" aria-hidden="true"><path d="M100 30 Q96 80 100 110 Q100 120 100 145" stroke="currentColor" strokeWidth="5" fill="none" strokeLinecap="round"/><ellipse cx="100" cy="145" rx="16" ry="26" fill="currentColor"/><circle cx="100" cy="30" r="6" fill="currentColor"/></svg>`;',
  '',
  'export function ${name}({ level, onChange, className }: ${name}Props) {',
  '  return (',
  '    <div className={`spoon-dial ${className || \\\'\\\'}`} role="radiogroup" aria-label="Cognitive load">',
  '      {Array.from({ length: 6 }, (_, i) => (',
  '        <button',
  '          key={i}',
  '          type="button"',
  '          className={`spoon-btn ${i === level ? \\\'active\\\' : \\\'\\\'}`}',
  '          onClick={() => onChange?.(i)}',
  '          role="radio"',
  '          aria-checked={i === level}',
  '          aria-label={`Spoons = ${i}`}',
  '          title={`Cognitive load level ${i}`}',
  '        >',
  '          <span dangerouslySetInnerHTML={{ __html: SPOON_SVG }} />',
  '        </button>',
  '      ))}',
  '    </div>',
  '  );',
  '}',
  '',
  'export default ${name};',
  '`,',
  '',
  '  Button: (name, def) => `/**',
  ' * @file ${name} — Primary action button.',
  ' * Auto-generated from components.yml.',
  ' */',
  '',
  'import type { ReactNode } from \'react\';',
  '',
  'export interface ${name}Props {',
  '  children: ReactNode;',
  '  variant?: \\\'primary\\\' | \\\'secondary\\\' | \\\'ghost\\\';',
  '  disabled?: boolean;',
  '  onClick?: () => void;',
  '  type?: \\\'button\\\' | \\\'submit\\\' | \\\'reset\\\';',
  '  className?: string;',
  '}',
  '',
  'export function ${name}({ children, variant = \\\'primary\\\', disabled, onClick, type = \\\'button\\\', className }: ${name}Props) {',
  '  return (',
  '    <button',
  '      type={type}',
  '      className={`btn btn-${variant} ${className || \\\'\\\'}`}',
  '      disabled={disabled}',
  '      onClick={onClick}',
  '    >',
  '      {children}',
  '    </button>',
  '  );',
  '}',
  '',
  'export default ${name};',
  '`,',
];

lines.splice(insertIndex, 0, ...newTemplates);
writeFileSync(path, lines.join('\n'), 'utf-8');
console.log('Added new component templates to React adapter');
