import { readFileSync, writeFileSync } from 'fs';

const path = 'src/generator/adapters/astro.ts';
const lines = readFileSync(path, 'utf-8').split('\n');

// Find line 380 (0-indexed: 379) which is the closing }; of COMPONENT_TEMPLATES
const insertIndex = lines.findIndex((line, i) => i === 379 && line.trim() === '};');
if (insertIndex === -1) {
  console.error('Could not find insertion point at line 380');
  console.error('Line 380 content:', lines[379]);
  process.exit(1);
}

const newTemplates = [
  '',
  '  Topbar: (name, def) => `---',
  '// @file ${name} — Fixed glass navigation header.',
  '// Auto-generated from components.yml.',
  '',
  'interface Props {',
  '  brand?: AstroSlotChildren;',
  '  left?: AstroSlotChildren;',
  '  center?: AstroSlotChildren;',
  '  right?: AstroSlotChildren;',
  '  class?: string;',
  '}',
  '',
  'const { brand, left, center, right, class: className = \\\'\' } = Astro.props;',
  '---',
  '',
  '<header class={`topbar glass-navbar ${className}`}>',
  '  <div class="topbar-left">{brand || left}</div>',
  '  <div class="topbar-center">{center}</div>',
  '  <div class="topbar-right">{right}</div>',
  '</header>',
  '`,',
  '',
  '  BottomNav: (name, def) => `---',
  '// @file ${name} — Fixed bottom navigation bar for mobile-first apps.',
  '// Auto-generated from components.yml.',
  '',
  'interface Props {',
  '  items: { icon: AstroSlotChildren; label: string; href: string; active?: boolean }[];',
  '  activeIndex?: number;',
  '  class?: string;',
  '}',
  '',
  'const { items, activeIndex = 0, class: className = \\\'\' } = Astro.props;',
  '---',
  '',
  '<nav class={`bottom-nav ${className}`} role="navigation" aria-label="Main">',
  '  {items.map((item, i) => (',
  '    <a',
  '      key={i}',
  '      href={item.href}',
  '      class={`nav-item ${i === activeIndex ? \\\'active\\\' : \\\'\\\'}`}',
  '      aria-current={i === activeIndex ? \\\'page\\\' : undefined}',
  '    >',
  '      {item.icon}',
  '      <span>{item.label}</span>',
  '    </a>',
  '  ))}',
  '</nav>',
  '`,',
  '',
  '  SpoonDial: (name, def) => `---',
  '// @file ${name} — Cognitive load selector (0-5 spoons).',
  '// Auto-generated from components.yml.',
  '',
  'interface Props {',
  '  level: number;',
  '  onChange?: (level: number) => void;',
  '  class?: string;',
  '}',
  '',
  'const { level, onChange, class: className = \\\'\' } = Astro.props;',
  '---',
  '',
  '<div class={`spoon-dial ${className}`} role="radiogroup" aria-label="Cognitive load">',
  '  {Array.from({ length: 6 }, (_, i) => (',
  '    <button',
  '      type="button"',
  '      class={`spoon-btn ${i === level ? \\\'active\\\' : \\\'\\\'}`}',
  '      onClick={() => onChange?.(i)}',
  '      role="radio"',
  '      aria-checked={i === level}',
  '      aria-label={`Spoons = ${i}`}',
  '      title={`Cognitive load level ${i}`}',
  '    />',
  '  ))}',
  '</div>',
  '`,',
  '',
  '  Button: (name, def) => `---',
  '// @file ${name} — Primary action button.',
  '// Auto-generated from components.yml.',
  '',
  'interface Props {',
  '  children: AstroSlotChildren;',
  '  variant?: \\\'primary\\\' | \\\'secondary\\\' | \\\'ghost\\\';',
  '  class?: string;',
  '}',
  '',
  'const { children, variant = \\\'primary\\\', class: className = \\\'\' } = Astro.props;',
  '---',
  '',
  '<button class={`btn btn-${variant} ${className}`}>',
  '  <slot />',
  '</button>',
  '`,',
];

lines.splice(insertIndex, 0, ...newTemplates);
writeFileSync(path, lines.join('\n'), 'utf-8');
console.log('Added new component templates to Astro adapter');
