#!/usr/bin/env node
/**
 * Token compiler — emits CSS custom properties + W3C DTCG JSON from canonical THEME_TOKENS.
 *
 * Outputs (deterministic, committed):
 *   src/generated/color-palette.css   ramp + semantic vars (from src/tokens/*.ts)
 *   src/generated/spoon-ladder.css    [data-spoons] motion/blur/opacity overrides
 *   src/generated/typography-scale.css type scale + weight tokens
 *   src/css/theme-{id}.css            [data-theme] blocks for each world
 *   src/mcp/tokens-data.ts            TOKEN_MAP + TOKENS_DATA for MCP explorer
 *   src/mcp/tokens.dtc.json           W3C Design Tokens Format Module 2025.10
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { colorRamps, RAMP_STEPS, RAMP_BASE_INDEX } from '../src/tokens/color.js';
import { fontStacks, fontWeightTokens, typographyScale } from '../src/tokens/typography.js';
import { motionTokens, spoonLadder } from '../src/tokens/motion.js';
import { THEME_TOKENS, type ThemeId } from '../src/theming/theme-store.js';

const OUT = join(dirname(fileURLToPath(import.meta.url)), '../src/generated');
const CSS_OUT = join(dirname(fileURLToPath(import.meta.url)), '../src/css');
const MCP_OUT = join(dirname(fileURLToPath(import.meta.url)), '../src/mcp');
mkdirSync(OUT, { recursive: true });
mkdirSync(CSS_OUT, { recursive: true });
mkdirSync(MCP_OUT, { recursive: true });

const banner = (name: string) =>
  `/* GENERATED by scripts/gen-tokens.mts — source: ${name}. Do not edit. */\n`;

// ── color-palette.css ────────────────────────────────────────────
let css = banner('src/tokens/color.ts');
for (const [ramp, shades] of Object.entries(colorRamps)) {
  shades.forEach((hex, i) => {
    const step = RAMP_STEPS[i] ?? '950';
    css += `--p31-${ramp}-${step}: ${hex};\n`;
    if (i === RAMP_BASE_INDEX) css += `--p31-${ramp}: ${hex};\n`;
  });
}
css += `\n/* Semantic aliases (light default) */\n`;
css += `:root {\n  color-scheme: light dark;\n}\n`;
css += `\n@media (prefers-color-scheme: dark) {\n:root {\n`;
css += `  --p31-accent-50: var(--p31-neutral-900);\n`;
css += `}\n}\n`;
writeFileSync(join(OUT, 'color-palette.css'), css);

// ── spoon-ladder.css ─────────────────────────────────────────────
let ladder = banner('src/tokens/motion.ts');
ladder += `:root {\n`;
ladder += `  --p31-motion-fast: ${motionTokens.fast};\n`;
ladder += `  --p31-motion-normal: ${motionTokens.normal};\n`;
ladder += `  --p31-motion-slow: ${motionTokens.slow};\n`;
ladder += `  --p31-motion-easing-in: ${motionTokens.easeIn};\n`;
ladder += `  --p31-motion-easing-out: ${motionTokens.easeOut};\n`;
ladder += `  --p31-motion-easing-inout: ${motionTokens.easeInOut};\n`;
ladder += `}\n`;
for (const s of spoonLadder) {
  ladder += `\n[data-spoons="${s.level}"] {\n`;
  ladder += `  --p31-motion-fast: ${s.motion};\n`;
  ladder += `  --p31-motion-normal: ${s.motion};\n`;
  ladder += `  --p31-motion-slow: ${s.level <= 1 ? '0ms' : motionTokens.slow};\n`;
  ladder += `  --p31-glass-blur: ${s.blur};\n`;
  if (s.level <= 1) {
    ladder += `  --p31-glass-bg: var(--p31-surface);\n`;
    ladder += `  --p31-glass-bg-strong: var(--p31-surface);\n`;
    ladder += `  --p31-text-secondary: var(--p31-text);\n`;
  }
  ladder += `}\n`;
}
writeFileSync(join(OUT, 'spoon-ladder.css'), ladder);

// ── typography-scale.css ─────────────────────────────────────────
let type = banner('src/tokens/typography.ts');
type += `:root {\n`;
type += `  --p31-font-weight-body: ${fontWeightTokens.body};\n`;
type += `  --p31-font-weight-emphasis: ${fontWeightTokens.emphasis};\n`;
for (const [k, v] of Object.entries(typographyScale)) type += `  --p31-type-${k}: ${v};\n`;
type += `  --p31-font-stack-sans: ${fontStacks.sans};\n`;
type += `  --p31-font-stack-mono: ${fontStacks.mono};\n`;
type += `}\n`;
writeFileSync(join(OUT, 'typography-scale.css'), type);

// ── theme-{id}.css ───────────────────────────────────────────────
for (const [id, tokens] of Object.entries(THEME_TOKENS)) {
  let themeCss = banner(`src/theming/theme-store.ts (${id})`);
  themeCss += `[data-theme="${id}"] {\n`;
  for (const [key, value] of Object.entries(tokens)) {
    themeCss += `  ${key}: ${value};\n`;
  }
  themeCss += `}\n`;
  writeFileSync(join(CSS_OUT, `theme-${id}.css`), themeCss);
}

// ── tokens-data.ts ───────────────────────────────────────────────
const semanticKeys = [
  ['color.background.default', '--p31-bg', '{primitive.color.void}'],
  ['color.background.void', '--p31-void', '{primitive.color.void}'],
  ['color.background.alt', '--p31-surface', '{primitive.color.surface}'],
  ['color.background.alt2', '--p31-surface2', '{primitive.color.surface2}'],
  ['color.accent.default', '--p31-accent', '{primitive.color.accent}'],
  ['color.accent.variant', '--p31-accent-violet', '{primitive.color.violet}'],
  ['color.accent.gold', '--p31-accent-gold', '{primitive.color.gold}'],
  ['color.accent.green', '--p31-accent-green', '{primitive.color.green}'],
  ['color.accent.red', '--p31-accent-red', '{primitive.color.red}'],
  ['color.accent.iris', '--p31-accent-violet', '{primitive.color.iris}'],
  ['color.notification.gold', '--p31-notif-gold', '{primitive.color.gold}'],
  ['color.notification.green', '--p31-notif-green', '{primitive.color.green}'],
  ['color.notification.violet', '--p31-notif-violet', '{primitive.color.violet}'],
  ['color.notification.cyan', '--p31-notif-cyan', '{primitive.color.cyan}'],
  ['color.notification.rose', '--p31-notif-rose', '{primitive.color.red}'],
  ['color.text.primary', '--p31-text', '{primitive.color.text_primary}'],
  ['color.text.secondary', '--p31-text-secondary', '{primitive.color.text_secondary}'],
  ['color.text.tertiary', '--p31-text-tertiary', '{primitive.color.text_tertiary}'],
  ['color.status.online', '--p31-accent-green', '{primitive.color.green}'],
  ['color.status.offline', '--p31-text-tertiary', '{primitive.color.text_tertiary}'],
  ['color.status.warning', '--p31-accent-gold', '{primitive.color.gold}'],
  ['color.status.error', '--p31-accent-red', '{primitive.color.red}'],
  ['color.status.info', '--p31-accent', '{primitive.color.cyan}'],
] as const;

const ocean = THEME_TOKENS['ocean'] as Record<string, string>;
const tokensData = semanticKeys.map(([path, cssVar, raw]) =>
  `  {
    "path": "${path}",
    "cssVar": "${cssVar}",
    "value": "${ocean[cssVar]}",
    "raw": "${raw}"
  }`
).join(',\n');

const tokenMap: Record<string, { cssVar: string; value: string; raw: string }> = {};
for (const [path, cssVar, raw] of semanticKeys) {
  tokenMap[path] = { cssVar, value: ocean[cssVar], raw };
}

const dataTs = `// Auto-generated by scripts/gen-tokens.mts — DO NOT EDIT
export const TOKENS_DATA = [
${tokensData},
];

export const TOKEN_MAP: Record<string, { cssVar: string; value: string; raw: string }> = ${JSON.stringify(tokenMap)};
`;
writeFileSync(join(MCP_OUT, 'tokens-data.ts'), dataTs);

// ── tokens.dtc.json ───────────────────────────────────────────────
const DTCG_OUT = join(dirname(fileURLToPath(import.meta.url)), '../src/mcp');
mkdirSync(DTCG_OUT, { recursive: true });

function parseOklch(value: string): { colorSpace: string; components: [number, number, number]; alpha?: number } | null {
  const m = value.match(/oklch\(\s*([0-9.]+)\s+([0-9.]+)\s+([0-9.]+)(?:\s*\/\s*([0-9.]+))?\s*\)/);
  if (!m) return null;
  return {
    colorSpace: 'oklch',
    components: [parseFloat(m[1]), parseFloat(m[2]), parseFloat(m[3])],
    alpha: m[4] ? parseFloat(m[4]) : 1,
  };
}

function dtcgColorValue(value: string): any {
  const parsed = parseOklch(value);
  if (parsed) return parsed;
  return value;
}

const semanticMap: Record<string, { path: string[]; type: string; description: string }> = {
  '--p31-bg': { path: ['color', 'background', 'default'], type: 'color', description: 'Page background — deepest void' },
  '--p31-void': { path: ['color', 'background', 'void'], type: 'color', description: 'Void black — deepest surface' },
  '--p31-surface': { path: ['color', 'background', 'alt'], type: 'color', description: 'Primary surface — cards, panels' },
  '--p31-surface2': { path: ['color', 'background', 'alt2'], type: 'color', description: 'Secondary surface — elevated panels' },
  '--p31-accent': { path: ['color', 'accent', 'default'], type: 'color', description: 'Primary accent — interactive elements' },
  '--p31-accent-alt': { path: ['color', 'accent', 'variant'], type: 'color', description: 'Secondary accent — complementary hue' },
  '--p31-accent-violet': { path: ['color', 'accent', 'violet'], type: 'color', description: 'Violet accent — tertiary interactions' },
  '--p31-accent-gold': { path: ['color', 'accent', 'gold'], type: 'color', description: 'Gold accent — warnings, highlights' },
  '--p31-accent-green': { path: ['color', 'accent', 'green'], type: 'color', description: 'Green accent — success, online status' },
  '--p31-accent-red': { path: ['color', 'accent', 'red'], type: 'color', description: 'Red accent — error, critical states' },
  '--p31-notif-gold': { path: ['color', 'notification', 'gold'], type: 'color', description: 'Notification accent — medication/reminders' },
  '--p31-notif-green': { path: ['color', 'notification', 'green'], type: 'color', description: 'Notification accent — movement/wellness' },
  '--p31-notif-violet': { path: ['color', 'notification', 'violet'], type: 'color', description: 'Notification accent — social/messages' },
  '--p31-notif-cyan': { path: ['color', 'notification', 'cyan'], type: 'color', description: 'Notification accent — bonding/collaboration' },
  '--p31-notif-rose': { path: ['color', 'notification', 'rose'], type: 'color', description: 'Notification accent — grants/deadlines' },
  '--p31-text': { path: ['color', 'text', 'primary'], type: 'color', description: 'Primary text — highest contrast' },
  '--p31-text-secondary': { path: ['color', 'text', 'secondary'], type: 'color', description: 'Secondary text — supporting content' },
  '--p31-text-tertiary': { path: ['color', 'text', 'tertiary'], type: 'color', description: 'Tertiary text — captions, hints' },
  '--p31-glass-bg': { path: ['color', 'glass', 'background'], type: 'color', description: 'Glass background — translucent overlay' },
  '--p31-glass-border': { path: ['color', 'glass', 'border'], type: 'color', description: 'Glass border — subtle separation' },
};

function setNested(obj: any, path: string[], value: any) {
  let current = obj;
  for (let i = 0; i < path.length - 1; i++) {
    const key = path[i];
    if (!current[key] || typeof current[key] !== 'object') current[key] = {};
    current = current[key];
  }
  current[path[path.length - 1]] = value;
}

const dtcg: any = {
  $schema: 'https://design-tokens.github.io/community-group/format/1.0.0',
  $type: 'object',
};

for (const [cssVar, meta] of Object.entries(semanticMap)) {
  const value = ocean[cssVar as keyof typeof ocean];
  if (!value) continue;
  setNested(dtcg, meta.path, {
    $type: meta.type,
    $value: dtcgColorValue(value),
    $description: meta.description,
  });
}

writeFileSync(join(DTCG_OUT, 'tokens.dtc.json'), JSON.stringify(dtcg, null, 2));

const dtcgTs = `// Auto-generated by scripts/gen-tokens.mts — DO NOT EDIT
export const TOKENS_DTC = ${JSON.stringify(dtcg, null, 2)} as const;
`;
writeFileSync(join(DTCG_OUT, 'tokens-dtc.ts'), dtcgTs);

console.log('✅ generated:', [
  'color-palette.css',
  'spoon-ladder.css',
  'typography-scale.css',
  ...(Object.keys(THEME_TOKENS) as ThemeId[]).map(id => `theme-${id}.css`),
  'tokens-data.ts',
  'tokens.dtc.json',
  'tokens-dtc.ts',
].join(', '));
