#!/usr/bin/env node
/**
 * @p31/canon — gen-design.mjs
 *
 * Emit DESIGN.md — Google's open format (google-labs-code/design.md, Apache-2.0)
 * for describing a visual identity to coding agents. One file, two layers:
 *   - YAML front matter — machine-readable design tokens (normative values)
 *   - Markdown body — human-readable rationale (principles, dos/don'ts)
 *
 * The source of truth is the SAME theme-store.ts the canon's gen:tokens reads —
 * there is no second definition. The emitter reads the DTCG export
 * (tokens/tokens.dtc.json, generated by gen:tokens) for the base tokens, and
 * theme-store.ts for the theme list + semantic assignments.
 *
 * An agent (a coding CLI, the Loom's MCP surface) that reads
 * DESIGN.md gets exact values AND the why — the P31 canon's contract, in the
 * format the industry is converging on.
 *
 * Run: node scripts/gen-design.mjs  (from packages/canon, after gen:tokens)
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const DTCG = join(root, 'tokens', 'tokens.dtc.json');
const STORE = join(root, 'src', 'theming', 'theme-store.ts');
const OUT = join(root, 'DESIGN.md');

const failures = [];
const fail = (msg) => { failures.push(msg); };

if (!existsSync(DTCG)) fail(`missing ${DTCG} — run gen:tokens first`);
if (!existsSync(STORE)) fail(`missing ${STORE}`);
if (failures.length) {
  for (const f of failures) console.error('❌ ' + f);
  process.exit(1);
}

const dtcg = JSON.parse(readFileSync(DTCG, 'utf8'));
const store = readFileSync(STORE, 'utf8');

// ── Pull the base tokens out of the DTCG tree ─────────────────────────
// Structure: { p31: { 'base': { $value, $type }, 'scale-xs': {...}, ... },
//              themes: { <id>: { p31: {...} } } }
const p31 = dtcg?.p31 ?? {};
const baseTokens = Object.entries(p31).filter(([k]) => !Array.isArray(k)).map(([k, v]) => ({
  name: k,
  value: v?.$value ?? '',
  type: v?.$type ?? 'token',
}));

// ── Pull the theme list + semantic assignments from theme-store.ts ─────
const themeIds = [];
for (const m of store.matchAll(/^\s{2}([a-z][a-z0-9]*):\s*\{\s*\n\s*id:\s*'([^']+)'/gm)) {
  themeIds.push({ key: m[1], id: m[2] });
}

const accentOf = (themeBlock) => {
  const m = themeBlock.match(/'--p31-accent':\s*'([^']+)'/);
  return m ? m[1] : null;
};
// Find each theme block by its `id: '<id>'` line, then grab --p31-accent.
const themeAccents = {};
for (const t of themeIds) {
  const start = store.indexOf(`id: '${t.id}'`);
  if (start === -1) continue;
  const block = store.slice(start, start + 1600);
  themeAccents[t.id] = accentOf(block);
}

// ── Build the YAML front matter ─────────────────────────────────────────
const yaml = (s) => JSON.stringify(s);

const frontMatter = [
  '---',
  'name: "P31 Loom"',
  'description: "The P31 design canon — a family-first, agent-native design system. Human and agent, co-present."',
  `version: "${dtcg?.$extensions?.p31?.version ?? '2025.10'}"`,
  'license: "Apache-2.0"',
  '',
  'design_system:',
  '  semantics:',
  '    - "accessible by default (WCAG 2.2 AA minimum, family floor 48px targets)"',
  '    - "sensory-aware (muted / warmLight modes, prefers-reduced-motion collapse)"',
  '    - "agent-native (typed tokens, AAF manifest, DESIGN.md)"',
  '  themes:',
];

for (const t of themeIds) {
  const accent = themeAccents[t.id];
  frontMatter.push(`    - id: "${t.id}"${accent ? `\n      accent: "${accent}"` : ''}`);
}

frontMatter.push(
  '',
  'tokens:',
  '  colors:',
  '    surface: { bg: "--p31-bg", surface: "--p31-surface", surface2: "--p31-surface2" }',
  '    text: { primary: "--p31-text-primary", secondary: "--p31-text-secondary", tertiary: "--p31-text-tertiary" }',
  '    accent: { base: "--p31-accent", cyan: "--p31-accent-cyan", violet: "--p31-accent-violet",',
  '               gold: "--p31-accent-gold", green: "--p31-accent-green", red: "--p31-accent-red",',
  '               iris: "--p31-accent-iris" }',
  '    glass: { bg: "--p31-glass-bg", border: "--p31-glass-border", shadow: "--p31-glass-shadow" }',
  '  typography:',
  '    sans: "--p31-font-sans"',
  '    mono: "--p31-font-mono"',
  '  spacing: { base: "--p31-base", xs: "--p31-scale-xs", sm: "--p31-scale-sm", md: "--p31-scale-md",',
  '              lg: "--p31-scale-lg", xl: "--p31-scale-xl", "2xl": "--p31-scale-2xl" }',
  '  radius: { sm: "--p31-radius-sm", md: "--p31-radius-md", lg: "--p31-radius-lg", full: "--p31-radius-full" }',
  '',
  'components:',
  '  - "The Loom chapters (orb, color-pick, workshop) — see apps/loom/src/components/"',
  '  - "Companion view (the elder\'s window) — apps/loom/src/components/Companion.tsx"',
  '---',
  '',
);

// ── Build the markdown body ─────────────────────────────────────────────
const body = [
  '# P31 Loom — design system for agents',
  '',
  'The design system as a live graph: human and agent, co-present. This file is',
  'the agent-readable face of the P31 canon. Every value below is generated from',
  '`packages/canon/src/theming/theme-store.ts` — the single source of truth.',
  '',
  '## Principles',
  '',
  '1. **Family-first.** Touch targets are 48px minimum (`--p31-touch-min`), 56px',
  '   recommended, 64px large. This exceeds WCAG 2.2 AAA and Apple/Material guidance.',
  '2. **Accessible by default.** WCAG 2.2 AA minimum; contrast via OKLCH perceptual',
  '   math, not hex luck. `prefers-reduced-motion` collapses `--motion-scale` to',
  '   0.01 — it never sets `animation: none` (the phase machines depend on',
  '   `animationend`).',
  '3. **Sensory-aware.** Two sensory modes — `muted` (chroma down) and `warmLight`',
  '   (chroma up, warmth toward amber). Never a hardcoded hex in production code;',
  '   every color is a `var(--p31-*)` token.',
  '4. **Agent-native.** The canon exposes typed tokens (`P31TokenName`), a W3C',
  '   DTCG export, and an AAF manifest (`.well-known/agent-manifest.json`). The',
  '   Loom\'s log is the runtime: state folds over an append-only event log; the',
  '   log is tamper-evident (`prev_hash` chain, `/verify`).',
  '',
  '## Token map',
  '',
  `The base tokens below are the normative values. All are emitted from the`,
  `DTCG export (${baseTokens.length} base tokens); semantic slots resolve through`,
  `the theme store.`,
  '',
];

// Token table
if (baseTokens.length) {
  body.push('| Token | Value | Type |');
  body.push('|---|---|---|');
  for (const t of baseTokens.slice(0, 24)) {
    const value = String(t.value).replace(/\|/g, '\\|');
    body.push(`| \`--p31-${t.name}\` | \`${value}\` | ${t.type} |`);
  }
  if (baseTokens.length > 24) body.push(`| … | ${baseTokens.length - 24} more base tokens | |`);
  body.push('');
}

body.push(
  '## Themes',
  '',
  ...themeIds.map((t) => `- **${t.id}**${themeAccents[t.id] ? ` — accent \`${themeAccents[t.id]}\`` : ''}`),
  '',
  '## Do / Don\'t',
  '',
  '- **Do** use `var(--p31-*)` tokens; never hardcode hex, rgba, or inline styles.',
  '- **Do** keep touch targets ≥ 48px for anything a child or elder touches.',
  '- **Do** respect `prefers-reduced-motion` (collapse, not disable).',
  '- **Don\'t** add a second source of truth for tokens — edit `theme-store.ts`.',
  '- **Don\'t** put PII in the log; the log is an artifact record, not a person record.',
  '- **Don\'t** make the agent write registry.json, contracts, or CSS directly —',
  '  it appends events; a human approves them through the gate.',
  '',
  '## Generated',
  '',
  `This file is generated by \`node scripts/gen-design.mjs\` from the DTCG export`,
  `(tokens/tokens.dtc.json) + theme-store.ts. Do not edit by hand; edit the source`,
  `and re-run \`pnpm gen:design\`.`,
  '',
);

const md = frontMatter.join('\n') + body.join('\n');
writeFileSync(OUT, md);
console.log(`DESIGN.md emitted (${OUT}) — ${baseTokens.length} base tokens, ${themeIds.length} themes, ${md.length} bytes.`);