import type { PassportDocument } from '@p31/shared/cognitive-passport';
import { getVisitLogs, type VisitLog } from './db';
import { loadDraft } from '../passport/lib/db/index';

export interface PassportFields {
  pii?: { givenName?: string; familyName?: string };
  med?: { diagnoses?: string[]; medications?: string[]; calcium?: string; pth?: string; vitaminD?: string };
  cog?: { neurotype?: string; sensorySensitivity?: number; executiveFunctionPatterns?: string };
  comm?: { modality_order?: string };
  fam?: { relationships?: Array<{ name?: string; role?: string }> };
}

export interface ADAInput {
  passport: { fields: PassportFields };
  visitationLogs: VisitLog[];
}

function getField<T>(obj: unknown, path: string, fallback: T): T {
  return (path.split('.').reduce((o: Record<string, unknown>, key: string) => o?.[key], obj) as T) ?? fallback;
}

export function assembleADADocument(input: ADAInput): string {
  const fields = input.passport.fields ?? {};
  const logs = input.visitationLogs;

  const name = getField(fields, 'pii.givenName', '[Name]');
  const neurotype = getField(fields, 'cog.neurotype', 'AuDHD');
  const sensorySensitivity = getField(fields, 'cog.sensorySensitivity', 0);
  const efPatterns = getField(fields, 'cog.executiveFunctionPatterns', 'Not specified');
  const commPrefs = getField(fields, 'comm.modality_order', 'Not specified');
  const diagnoses = getField<string[]>(fields, 'med.diagnoses', []);
  const medications = getField<string[]>(fields, 'med.medications', []);
  const calcium = getField(fields, 'med.calcium', 'N/A');
  const pth = getField(fields, 'med.pth', 'N/A');
  const vitaminD = getField(fields, 'med.vitaminD', 'N/A');

  let md = '# ADA Accommodation Request & Contempt Motion\n\n';
  md += `**Date:** ${new Date().toLocaleDateString()}\n\n`;
  md += `**Operator:** ${name}\n\n`;

  md += '## 1. Biological & Medical Context\n\n';
  md += `- **Diagnoses:** ${(diagnoses ?? []).join(', ') || 'Not specified'}\n`;
  md += `- **Current medications:** ${(medications ?? []).join(', ') || 'Not specified'}\n`;
  md += `- **Relevant labs:** Ca ${calcium}, PTH ${pth}, Vitamin D ${vitaminD}\n\n`;

  md += '## 2. Neurocognitive Profile\n\n';
  md += `- **Neurotype:** ${neurotype}\n`;
  md += `- **Sensory sensitivity (0-10):** ${sensorySensitivity}\n`;
  md += `- **Executive function patterns:** ${efPatterns}\n`;
  md += `- **Communication preferences:** ${commPrefs}\n\n`;

  md += '## 3. Visitation Log Summary\n\n';
  if (logs.length === 0) {
    md += '_No visitation logs recorded yet._\n\n';
  } else {
    md += '| Date | Duration | Supervisor | Deviations |\n';
    md += '|------|----------|------------|------------|\n';
    for (const log of logs) {
      md += `| ${log.date} | ${log.duration} min | ${log.supervisor || 'N/A'} | ${log.deviations || 'None'} |\n`;
    }
    md += '\n';
  }

  md += '## 4. Requested Accommodations (ADA Title II)\n\n';
  md += 'Based on the above, I request the following accommodations:\n\n';
  md += '1. **Medical:** Calcium/PTH monitoring schedule continuity during all required events (exhibit A).\n';
  md += '2. **Sensory:** Ability to step away for decompression to prevent autonomic overload (exhibit B).\n';
  md += '3. **Communication:** Written instructions/updates provided asynchronously (48 hours in advance) (exhibit C).\n';
  md += '4. **Legal:** Contempt motion for failure to comply with existing environmental orders (exhibit D).\n\n';

  md += '## 5. Conclusion\n\n';
  md += 'This document is submitted in good faith to ensure equitable participation and health safety. I request an expedited hearing.\n\n';
  md += '---\n';
  md += `*Generated by P31 Tetrahedron ADA Assembler v1.0 on ${new Date().toISOString()}*\n`;

  return md;
}

export async function generateADADocument(): Promise<string> {
  const draft = await loadDraft('current-draft');
  const passport = draft?.data ?? { fields: {} };
  const rawLogs = await getVisitLogs(30);
  return assembleADADocument({ passport, visitationLogs: rawLogs });
}
