/**
 * @p31/field — adapters.ts
 *
 * The bridge from the real system to the Instrument's inputs. Two pure
 * functions, both deterministic:
 *
 *   zonesFromRegistry(registry)  — registry.json → Zone[] (the field's cells)
 *   tracesFromWarp(events)       — warp events  → Trace[] (the field's deposits)
 *
 * Neither function owns the data. The registry is generated by the canon
 * build; the warp is appended by the Loom. These adapters only read those
 * records and project them into the Field's vocabulary — so the Instrument
 * can read the field without knowing how the registry or the warp are
 * stored.
 *
 * Zone model (locked decision): every registry artifact is a zone — 299
 * today (169 tokens, 2 components, 118 classes, 10 themes). Frame tokens are
 * excluded — they are render metadata, not artifacts (see gen-registry.mjs).
 * Each zone is a
 * complete K₄ over the four artifact kinds {component, class, token, theme};
 * the artifact's own kind-vertex carries the artifact's name, the other
 * three carry the kind labels. A zone is rigid (β₂ = 1) iff it is a complete
 * K₄ — which it always is here, because a fully-registered artifact is fully
 * typed across the four kinds.
 *
 * Trace mapping (locked decision): warp events + weft reads. The mapping is
 * total — every warp event kind becomes exactly one Trace — and the frame (the
 * SIC-POVM-style four-lens frame from index.ts) is assigned by kind:
 *
 *   structure : propose, revise, review      (shape of the system; review is
 *              a judgement of the shape, not a movement)
 *   connection: focus, presence, view.save, view.read  (attention & reads)
 *   rhythm    : traverse                     (movement)
 *   creation  : approve, reject              (acceptance decisions)
 *
 * The Trace's zone field is the best node reference the event carries, so
 * pressure can land on a real artifact where one exists:
 *
 *   focus/traverse/presence/propose → event.node (a registry artifact)
 *   revise/approve/reject/review    → the proposal id (a loom object)
 *   view.save                       → `save:<label>` (a named read)
 */
import type { Zone, Trace, Frame, Coherence } from './index.ts';
import { makeZone } from './index.ts';

/** The four registry kinds — the Zone's measurement frame. */
const KINDS = ['component', 'class', 'token', 'theme'] as const;
type Kind = (typeof KINDS)[number];

/** Minimal registry surface. The canon build emits more; the adapter reads
 *  only what the Field needs. */
export interface Registry {
  counts?: { tokens?: number; components?: number; cssClasses?: number; themes?: number };
  tokens?: readonly { name: string }[];
  components?: readonly { slug: string; name?: string }[];
  cssClasses?: readonly { name: string }[];
  themes?: readonly { id: string }[];
}

/** The six edges of a complete K₄ over four named vertices, in a fixed order. */
function k4Edges(vertices: [string, string, string, string]): [string, string][] {
  return [
    [vertices[0], vertices[1]], [vertices[0], vertices[2]], [vertices[0], vertices[3]],
    [vertices[1], vertices[2]], [vertices[1], vertices[3]], [vertices[2], vertices[3]],
  ];
}

/** A zone whose `kind`-th vertex carries `name`, the rest carry kind labels. */
function artifactZone(name: string, kind: Kind): Zone {
  const vertices: [string, string, string, string] = [
    kind === 'component' ? name : 'component',
    kind === 'class' ? name : 'class',
    kind === 'token' ? name : 'token',
    kind === 'theme' ? name : 'theme',
  ];
  return makeZone(name, vertices, k4Edges(vertices));
}

/**
 * Registry → Zone[]. One zone per artifact, across all four kinds. Pure and
 * deterministic: the same registry produces the same zones, in registry
 * order (tokens, then components, then classes, then themes).
 */
export function zonesFromRegistry(registry: Registry): Zone[] {
  const zones: Zone[] = [];
  for (const t of registry.tokens ?? []) zones.push(artifactZone(t.name, 'token'));
  // The warp log references components by `name` (`Button`), not `slug`
  // (`button`); zone ids must match the log's bare names to receive pressure.
  for (const c of registry.components ?? []) zones.push(artifactZone(c.name ?? c.slug, 'component'));
  for (const k of registry.cssClasses ?? []) zones.push(artifactZone(k.name, 'class'));
  for (const th of registry.themes ?? []) zones.push(artifactZone(th.id, 'theme'));
  return zones;
}

/** Minimal warp event surface — the LoomEvent union, narrowed to what the
 *  adapter reads. Kept structural so it survives additions to the union. */
export interface WarpEvent {
  seq: number;
  ts: string;
  writer: 'human' | 'agent';
  kind: string;
  node?: string;
  /** `traverse` carries node names (string); `view.save` carries warpSeq
   *  (number). The adapter only reads `from`/`to` for `traverse`. */
  from?: string | number;
  to?: string | number;
  id?: string;
  body?: unknown;
  author?: string;
  proposal?: string;
  proposalId?: string;
  agent?: string;
  decision?: string;
  reason?: string;
  attention?: number;
  label?: string;
  humanId?: string;
}

/** Kind → frame, the four-lens assignment. */
const FRAME_BY_KIND: Record<string, Frame> = {
  propose: 'structure',
  revise: 'structure',
  review: 'structure',
  focus: 'connection',
  presence: 'connection',
  'view.save': 'connection',
  traverse: 'rhythm',
  approve: 'creation',
  reject: 'creation',
};

/** Kind → zone: the best node reference the event carries. */
function zoneOf(e: WarpEvent): string {
  switch (e.kind) {
    case 'focus':
    case 'propose':
    case 'presence':
      return e.node ?? '';
    case 'traverse':
      return (typeof e.to === 'string' && e.to) || (typeof e.from === 'string' && e.from) || '';
    case 'revise':
    case 'approve':
    case 'reject':
      return e.proposal ?? '';
    case 'review':
      return e.proposalId ?? '';
    case 'view.save':
      return `save:${e.label ?? ''}`;
    default:
      return '';
  }
}

/** Actor: humans are `humanId` (falling back to 'human'); agents are the
 *  event's own author/agent field (falling back to 'agent'). */
function actorOf(e: WarpEvent): string {
  if (e.writer === 'human') return e.humanId ?? 'human';
  return e.author ?? e.agent ?? 'agent';
}

/** Pre-image / post-image — Proof-of-Territory. Where an event carries a
 *  before/after (traverse), it is preserved; otherwise the after-state is the
 *  event's outcome, so `zeroUtility` (preImage === postImage) means "no
 *  delta", not "no content". */
function imagesOf(e: WarpEvent): { preImage: string; postImage: string } {
  switch (e.kind) {
    case 'traverse':
      return { preImage: typeof e.from === 'string' ? e.from : '', postImage: typeof e.to === 'string' ? e.to : '' };
    case 'propose':
      return { preImage: '', postImage: e.id ?? '' };
    case 'review':
      return { preImage: '', postImage: `${e.proposalId ?? ''}:${e.decision ?? ''}` };
    case 'approve':
    case 'reject':
      return { preImage: '', postImage: `${e.proposal ?? ''}:${e.kind}` };
    case 'focus':
    case 'presence':
      return { preImage: '', postImage: e.node ?? '' };
    case 'view.save':
      return { preImage: '', postImage: e.label ?? '' };
    case 'revise':
      return { preImage: e.proposal ?? '', postImage: JSON.stringify(e.body ?? null) };
    default:
      return { preImage: '', postImage: '' };
  }
}

/** Warp events → Trace[]. Total, deterministic: one trace per event, in log
 *  order, and an event the adapter cannot name still yields a trace (frame
 *  'structure', empty zone) rather than being dropped — the field is a
 *  record of everything, and "unnamed" is a reading, not an error. */
export function tracesFromWarp(events: readonly WarpEvent[]): Trace[] {
  return events.map((e) => {
    const { preImage, postImage } = imagesOf(e);
    return {
      actor: actorOf(e),
      zone: zoneOf(e),
      frame: FRAME_BY_KIND[e.kind] ?? 'structure',
      kind: e.kind,
      payload: e.body ?? (e.kind === 'review' ? { decision: e.decision, reason: e.reason } : null),
      preImage,
      postImage,
      coherence: 'in-lane' as Coherence,
      ts: Date.parse(e.ts),
    };
  });
}

/** Minimal weft surface — narrowed to the read the Field cares about. */
export interface WeftEventLike {
  kind: string;
  ts: string;
  humanId?: string;
  focus?: string | null;
  scale?: string;
  entropy?: number;
  whiteSpace?: number;
}

/**
 * Weft reads → Trace[]. The "reading is writing" loop: a focused `view.read`
 * deposits a connection trace at the zone the viewer read, so the viewer's
 * attention becomes part of the field. Stigmergy, not metaphor (ANTON-SIFTA,
 * app_focus principle: "attention itself becomes a strong stigmergic signal").
 *
 * Only focused reads map — a constellation read (`focus: null`) is a read of
 * the whole field, not attention to one zone, so it writes a weft line but
 * deposits no trace. `view.pin`/`field.decision` are operational telemetry,
 * not field deposits, and are deliberately not mapped.
 */
export function tracesFromWeft(events: readonly WeftEventLike[]): Trace[] {
  return events
    .filter((e) => e.kind === 'view.read' && typeof e.focus === 'string' && e.focus.length > 0)
    .map((e) => ({
      actor: e.humanId ?? 'human',
      zone: e.focus as string,
      frame: 'connection' as Frame,
      kind: 'view.read',
      payload: { scale: e.scale, entropy: e.entropy, whiteSpace: e.whiteSpace },
      preImage: '',
      postImage: `${e.scale ?? 'constellation'}:${e.focus}`,
      coherence: 'in-lane' as Coherence,
      ts: Date.parse(e.ts),
    }));
}
